spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    com.example.blogsearch: debug

feign:
  client:
    config:
      default:
        loggerLevel: FULL

external-client:
  daum:
    url: 'https://dapi.kakao.com'
    authorization: 'KakaoAK 8502d649cb53a5b40f0e39fe9f52d24a'
  naver:
    url: 'https://openapi.naver.com'
    client-id: 'FcqOM0eREChjs51tYe3v'
    client-secret: 'vD3moqYh5y'